force-app/main/default/objects/DocumentList__c/DocumentList__c.object-meta.xml
<CustomObject>
    <description>Represents a list of documents</description>
    <label>Document List</label>
    <nameField>
        <label>Document List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentList__c/fields/CheckboxField__c.field-meta.xml
<CustomField>
    <fullName>CheckboxField__c</fullName>
    <description>Api Name of the checkbox field that is checked when all documents have been approved</description>
    <inlineHelpText>Api Name of the checkbox field that is checked when all documents have been approved</inlineHelpText>
    <label>Checkbox Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentList__c/fields/ObjectApiName__c.field-meta.xml
<CustomField>
    <fullName>ObjectApiName__c</fullName>
    <description>The Object API Name to which this list of documents will be attached</description>
    <inlineHelpText>The Object API Name to which this list of documents will be attached</inlineHelpText>
    <label>Object Api Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentListAssignment__c/DocumentListAssignment__c.object-meta.xml
<CustomObject>
    <description>Used to assign records to document lists</description>
    <label>Document List Assignment</label>
    <nameField>
        <displayFormat>DLA-{00000}</displayFormat>
        <label>Document List Assignement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document List Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentListAssignment__c/fields/Criteria__c.field-meta.xml
<CustomField>
    <fullName>Criteria__c</fullName>
    <description>Assign the document bundle only when this criteria evaluates to TRUE. Example : BillingCountry = &apos;Italy&apos;</description>
    <inlineHelpText>Assign the document bundle only when this criteria evaluates to TRUE. Example : BillingCountry = &apos;Italy&apos;</inlineHelpText>
    <label>Criteria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentListAssignment__c/fields/DocumentList__c.field-meta.xml
<CustomField>
    <fullName>DocumentList__c</fullName>
    <label>Document List</label>
    <referenceTo>DocumentList__c</referenceTo>
    <relationshipLabel>Document List Assignments</relationshipLabel>
    <relationshipName>DocumentListAssignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DocumentListAssignment__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates if the assignment is active.</description>
    <inlineHelpText>Indicates if the assignment is active.</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DocumentListItem__c/DocumentListItem__c.object-meta.xml
<CustomObject>
    <description>Item of the documents list</description>
    <label>Document List Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document List Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentListItem__c/fields/CheckboxField__c.field-meta.xml
<CustomField>
    <fullName>CheckboxField__c</fullName>
    <description>Api Name of the Checkbox field that is checked when the document is uploaded</description>
    <inlineHelpText>Api Name of the Checkbox field that is checked when the document is uploaded</inlineHelpText>
    <label>Checkbox Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentListItem__c/fields/DocumentList__c.field-meta.xml
<CustomField>
    <fullName>DocumentList__c</fullName>
    <label>Document List</label>
    <referenceTo>DocumentList__c</referenceTo>
    <relationshipLabel>Document List Items</relationshipLabel>
    <relationshipName>ListItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DocumentListItem__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>Represents the order of the document in the list.</description>
    <inlineHelpText>Represents the order of the document in the list.</inlineHelpText>
    <label>Order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DocumentManagerTestFactory.cls
public without sharing class DocumentManagerTestFactory {

    // generate a doc list
    public static DocumentList__c getDocumentList(String sObjectName, String checkboxField, boolean doInsert) {
        DocumentList__c dl = new DocumentList__c();
        dl.Name = 'Test doc list '+Datetime.now();
        dl.IsActive__c = true;
        dl.ObjectApiName__c = sObjectName;
        dl.CheckboxField__c = checkboxField;
        dl.Description__c = 'Document list test';
        if(doInsert) {
            insert dl;
        }
        return dl;
    }

    // generate a doc list item
    public static DocumentListItem__c getDocumentListItem(Id docListId, boolean isRequired, Integer docOrder, String checkboxField, boolean doInsert) {
        DocumentListItem__c dli = new DocumentListItem__c();
        dli.Name = 'Test doc list '+Datetime.now();
        dli.DocumentList__c = docListId;
        dli.IsActive__c = true;
        dli.Required__c = isRequired;
        dli.CheckboxField__c = checkboxField;
        dli.Description__c = 'Test doc list item';
        dli.Order__c = docOrder;
        if(doInsert) {
            insert dli;
        }
        return dli;
    }

    // generate a doc list assignment
    public static DocumentListAssignment__c getDocumentListAssignment(Id docListId, boolean doInsert) {
        DocumentListAssignment__c dla = new DocumentListAssignment__c();
        dla.DocumentList__c = docListId;
        dla.IsActive__c = true;
        dla.Criteria__c = 'Id != null';
        if(doInsert) {
            insert dla;
        }
        return dla;
    }

    // Campaign
    public static Campaign getCampaign(boolean doInsert) {
        Campaign c = new Campaign();
        c.Name = 'random campaign '+Datetime.now();
        
        if(doInsert) {
            insert c;
        }
        return c;
    }
}