force-app/main/default/objects/DocumentList__c/DocumentList__c.object-meta.xml
<CustomObject>
    <description>Represents a list of documents</description>
    <label>Document List</label>
    <nameField>
        <label>Document List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentList__c/fields/CheckboxField__c.field-meta.xml
<CustomField>
    <fullName>CheckboxField__c</fullName>
    <description>Api Name of the checkbox field that is checked when all documents have been approved</description>
    <inlineHelpText>Api Name of the checkbox field that is checked when all documents have been approved</inlineHelpText>
    <label>Checkbox Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DocumentList__c/fields/ObjectApiName__c.field-meta.xml
<CustomField>
    <fullName>ObjectApiName__c</fullName>
    <description>The Object API Name to which this list of documents will be attached</description>
    <inlineHelpText>The Object API Name to which this list of documents will be attached</inlineHelpText>
    <label>Object Api Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DocumentListTriggerHelper.cls
public without sharing class DocumentListTriggerHelper {

    public class DocumentListException extends Exception {}

    public static void onAfterInsert(Map<Id, DocumentList__c> newLists) {
        validateObjectAndCheckboxField(newLists);
    }

    public static void onAfterUpdate(Map<Id, DocumentList__c> newLists, Map<Id, DocumentList__c> oldLists) {
        validateObjectAndCheckboxField(newLists);
    }

    // check values on parent when doc is approved
    private static void validateObjectAndCheckboxField(Map<Id, DocumentList__c> newLists) {
        for(DocumentList__c dl : newLists.values()) {
            if(dl.ObjectApiName__c != null) {

                if(!DocumentManagerUtils.isValidObjectStr(dl.ObjectApiName__c)) {
                    throw new DocumentListException('The object name '+dl.ObjectApiName__c+' is not valid.');
                }

                if(dl.CheckboxField__c != null) {
                    if(!DocumentManagerUtils.hasField(dl.ObjectApiName__c, dl.CheckboxField__c)) {
                        throw new DocumentListException('The object '+dl.ObjectApiName__c+' has no field with name '+dl.CheckboxField__c+'.');
                    }

                    if(String.valueOf(DocumentManagerUtils.getFieldType(dl.ObjectApiName__c, dl.CheckboxField__c)) != 'BOOLEAN' ) {
                        throw new DocumentListException('The field '+dl.CheckboxField__c+ ' is not a checkbox.');
                    }
                }
            }
        }
    }
}