force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <description>Represents a document related to a record</description>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Document_Order__c.field-meta.xml
<CustomField>
    <fullName>Document_Order__c</fullName>
    <label>Document Order</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/DocumentList__c.field-meta.xml
<CustomField>
    <fullName>DocumentList__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Document List</label>
    <referenceTo>DocumentList__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/DocumentListItem__c.field-meta.xml
<CustomField>
    <fullName>DocumentListItem__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Document List Item</label>
    <referenceTo>DocumentListItem__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <description>Represents the record Id to which the document is related.</description>
    <inlineHelpText>Represents the record Id to which the document is related.</inlineHelpText>
    <label>RecordId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates the status of the document</description>
    <inlineHelpText>Indicates the status of the document</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Missing</fullName>
                <default>true</default>
                <label>Missing</label>
            </value>
            <value>
                <fullName>Uploaded</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DocumentList__c/DocumentList__c.object-meta.xml
<CustomObject>
    <description>Represents a list of documents</description>
    <label>Document List</label>
    <nameField>
        <label>Document List Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Lists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentListAssignment__c/DocumentListAssignment__c.object-meta.xml
<CustomObject>
    <description>Used to assign records to document lists</description>
    <label>Document List Assignment</label>
    <nameField>
        <displayFormat>DLA-{00000}</displayFormat>
        <label>Document List Assignement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document List Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentListAssignment__c/fields/DocumentList__c.field-meta.xml
<CustomField>
    <fullName>DocumentList__c</fullName>
    <label>Document List</label>
    <referenceTo>DocumentList__c</referenceTo>
    <relationshipLabel>Document List Assignments</relationshipLabel>
    <relationshipName>DocumentListAssignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DocumentListItem__c/DocumentListItem__c.object-meta.xml
<CustomObject>
    <description>Item of the documents list</description>
    <label>Document List Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document List Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DocumentListItem__c/fields/DocumentList__c.field-meta.xml
<CustomField>
    <fullName>DocumentList__c</fullName>
    <label>Document List</label>
    <referenceTo>DocumentList__c</referenceTo>
    <relationshipLabel>Document List Items</relationshipLabel>
    <relationshipName>ListItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DocumentManagerTest.cls
@isTest
public without sharing class DocumentManagerTest {

    @isTest
    public static void testDocManager() {

        DocumentList__c docList = DocumentManagerTestFactory.getDocumentList('Campaign', 'IsActive', true); // creae a doc list
        DocumentListItem__c requiredDocListItem = DocumentManagerTestFactory.getDocumentListItem(docList.Id, true, 1, null, true); // create an item
        DocumentListItem__c optionalDocListItem = DocumentManagerTestFactory.getDocumentListItem(docList.Id, false, 2, null, true); // create an item
        DocumentListAssignment__c docListAssignment = DocumentManagerTestFactory.getDocumentListAssignment(docList.Id, true); // create a doc list assignment
        
        Campaign c = DocumentManagerTestFactory.getCampaign(true); // create a task

        Test.startTest();

            // get doc lists
            GetDocumentListsInvoc.Request request = new GetDocumentListsInvoc.Request();
            request.recordId = c.Id;
            List<GetDocumentListsInvoc.Request> requests = new List<GetDocumentListsInvoc.Request>();
            requests.add(request);
            List<GetDocumentListsInvoc.Response> responses = GetDocumentListsInvoc.getDocumentLists(requests);
            System.debug('>>> responses '+responses);
            System.assertEquals(responses.size(), 1);
            System.assertEquals(responses[0].isSuccess, true, responses[0].message);
            System.assertEquals(responses[0].documentLists.size(), 1);
            System.assertEquals(responses[0].documentLists[0].Id, docList.Id);
            
            // generate docs for a specific list
            InitDocumentsInvoc.Request req = new InitDocumentsInvoc.Request();
            req.listId = docList.Id;
            req.recordId = c.Id;
            req.reset = true;

            List<InitDocumentsInvoc.Request> reqs = new List<InitDocumentsInvoc.Request>();
            reqs.add(req);

            List<InitDocumentsInvoc.Response> initResponses = InitDocumentsInvoc.initDocuments(reqs);
            System.debug('>>> responses '+initResponses);
            
            System.assertEquals(initResponses.size(), 1); // assert 1 response
            System.assertEquals(initResponses[0].isSuccess, true, initResponses[0].message); // assert success true or show message
            
        Test.stopTest();
        
        // check that docs were created
        List<Document__c> docs = [SELECT Id, Status__c, Document_Order__c, DocumentList__c, DocumentListItem__c FROM Document__c WHERE RecordId__c =: c.Id];
        System.assertEquals(docs.size(), 2);

        // verify that the checkbox is not set to true
        Campaign cUp = [SELECT Id, IsActive FROM Campaign WHERE Id = :c.Id];
        System.assertEquals(cUp.IsActive, false);

        // approve required doc
        Document__c requiredDoc = [SELECT Id FROM Document__c WHERE DocumentListItem__r.Required__c = true];
        requiredDoc.Status__c = 'Approved';
        update requiredDoc;
        
        // vertify that the checkbox is now true, since the doc is approved
        Campaign cUp2 = [SELECT Id, IsActive FROM Campaign WHERE Id = :c.Id];
        System.assertEquals(cUp2.IsActive, true);

        // approve required doc
        Document__c optionalDoc = [SELECT Id FROM Document__c WHERE DocumentListItem__r.Required__c = false];
        delete optionalDoc;
        
        // vertify that the checkbox is still true 
        Campaign cUp3 = [SELECT Id, IsActive FROM Campaign WHERE Id = :c.Id];
        System.assertEquals(cUp3.IsActive, true);
    }
}