force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <description>Represents a document related to a record</description>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <description>Represents the record Id to which the document is related.</description>
    <inlineHelpText>Represents the record Id to which the document is related.</inlineHelpText>
    <label>RecordId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Indicates the status of the document</description>
    <inlineHelpText>Indicates the status of the document</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Missing</fullName>
                <default>true</default>
                <label>Missing</label>
            </value>
            <value>
                <fullName>Uploaded</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DocumentTriggerHelper.cls
public without sharing class DocumentTriggerHelper {
    
    public static void onAfterInsert(Map<Id, Document__c> newDocuments) {
        setParentCheckboxValues(newDocuments, null);
    }

    public static void onAfterUpdate(Map<Id, Document__c> newDocuments, Map<Id, Document__c> oldDocuments) {
        setParentCheckboxValues(newDocuments, oldDocuments);
    }

    public static void onAfterDelete(Map<Id, Document__c> oldDocuments) {
        setParentCheckboxValues(null, oldDocuments);
    }


    // check values on parent when doc is approved
    private static void setParentCheckboxValues(Map<Id, Document__c> newDocuments, Map<Id, Document__c> oldDocuments) {
        Set<Id> recordIdsToUpdate = new Set<Id>();
        if(newDocuments != null) {
            if(oldDocuments != null) {
                for(Document__c newDoc : newDocuments.values()) {
                    if(oldDocuments.containsKey(newDoc.Id)) {
                        Document__c oldDoc = oldDocuments.get(newDoc.Id);
                        if(newDoc.Status__c <> oldDoc.Status__c ||  newDoc.RecordId__c <> oldDoc.RecordId__c) {
                            if(newDoc.RecordId__c != null) {
                                recordIdsToUpdate.add(newDoc.RecordId__c);
                            }
                            if(oldDoc.RecordId__c != null) {
                                recordIdsToUpdate.add(oldDoc.RecordId__c);
                            }
                        }
                    }
                }
            } else {
                for(Document__c newDoc : newDocuments.values()) {
                    if(newDoc.RecordId__c != null) {
                        recordIdsToUpdate.add(newDoc.RecordId__c);
                    }
                }
            }
        } else {
            if(oldDocuments != null) {
                for(Document__c oldDoc : oldDocuments.values()) {
                    if(oldDoc.RecordId__c != null) {
                        recordIdsToUpdate.add(oldDoc.RecordId__c);
                    }
                }
            }
        }

        if(recordIdsToUpdate.size() > 0) {
            DocumentService.setParentCheckboxValues(recordIdsToUpdate);
        }
    }

}